version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - db
    command: gunicorn --bind 0.0.0.0:8000 drom.wsgi:application  # Use Gunicorn instead of runserver
    expose:
      - 8000  # Expose port internally (no need for host binding)

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount Nginx config
      - static_volume:/app/staticfiles:ro  # Read-only static files
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: