# Generated by Django 5.2 on 2025-04-30 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Model name')),
                ('model_url', models.URLField(verbose_name='Model URL')),
                ('image_url', models.URLField(verbose_name='Image URL')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Complectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Complectation name')),
                ('volume', models.CharField(max_length=50, verbose_name='Engine volume')),
                ('fuel_type', models.CharField(max_length=50, verbose_name='Fuel type')),
                ('power', models.CharField(max_length=50, verbose_name='Power')),
                ('transmission', models.CharField(max_length=50, verbose_name='Transmission type')),
                ('drive', models.CharField(max_length=50, verbose_name='Drive type')),
                ('price', models.CharField(max_length=50, verbose_name='Price')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complectations', to='server.car')),
            ],
            options={
                'verbose_name': 'Complectation',
                'verbose_name_plural': 'Complectations',
            },
        ),
    ]
